steps:
  - label: "CI Plot and Doctests"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      os: "linux"
      arch: "x86_64"
    env:
      GROUP: QUANTUMSAVORY_PLOT_TEST